### ISSUE TITLE
Missing ARM64 support for Docker-Image

### ISSUE THREAD

**Issue by BluetonicBeats** [BlueprintFramework/docker#10]
I noticed that I get an error when pulling the blueprint docker image:                                                                                                                                  

```bash
0.9s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Which is caused by a missing arm64 image. Haven't got the error with the original Pterodactyl Panel. Can u add a builing process for ARM based CPUs as well?

**Comment by BluetonicBeats** [comment]
Workaround until native support is implemented is to tell the service to use the amd64 platform - which might result in problems:

Update: While the Docker Image gets pulled and the Docker Container started with the platform attribute, it crashes.

```
platform: linux/amd64
```

```yaml
  panel:
    platform: linux/amd64
    image: ghcr.io/blueprintframework/blueprint:v1.11.9
    restart: always
    ports:
      - "${PANEL_PORT}:${PANEL_PORT}"
    links:
      - database
      - cache
    volumes:
      - "${BASE_DIR}/var/:/app/var/"
      - "${BASE_DIR}/nginx/:/etc/nginx/http.d/"
      - "${BASE_DIR}/certs/:/etc/letsencrypt/live:ro"
      - "${BASE_DIR}/logs/:/app/storage/logs"
      - "/var/log/nginx:/var/log/nginx"
      - "/srv/pterodactyl/extensions/:/blueprint_extensions"
      - "app:/app"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production" # "production" or "testing"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      REDIS_PASSWORD: *redis-password
      DB_HOST: "database"
      DB_PORT: "3306"
      HASHIDS_SALT: "${HASH_SALT}"
      HASHIDS_LENGTH: 8
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${PANEL_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
```
